export const aboutUs = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'ABOUT US',
  headline: "UNC AASA",
  description: "The purpose of UNC's Asian American Students Association is to advance the interests and needs of UNC’s Asian/Asian-American student population by providing members with the resources and opportunities to define for themselves the Asian American’s role as part of American culture.",
  buttonLabel: 'Learn more',
  imgStart: false,
  dark: true,
  alt: 'photo of aasa',
  primary: true,
  darkText: false,
}
